# Generated by Django 4.2 on 2024-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='teaser_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
